export class countryList {
  public static countries = [
    {"Code": "AF", "name": "AFGHANISTAN"},
    {"Code": "AL", "name": "ALBANIA"},
    {"Code": "DZ", "name": "ALGERIA"},
    {"Code": "AS", "name": "AMERICAN SAMOA"},
    {"Code": "AD", "name": "ANDORRA"},
    {"Code": "AO", "name": "ANGOLA"},
    {"Code": "AI", "name": "ANGUILLA"},
    {"Code": "AQ", "name": "ANTARCTICA"},
    {"Code": "AG", "name": "ANTIGUA AND BARBUDA"},
    {"Code": "AR", "name": "ARGENTINA"},
    {"Code": "AM", "name": "ARMENIA"},
    {"Code": "AW", "name": "ARUBA"},
    {"Code": "AU", "name": "AUSTRALIA"},
    {"Code": "AT", "name": "AUSTRIA"},
    {"Code": "AZ", "name": "AZERBAIJAN"},
    {"Code": "BS", "name": "BAHAMAS"},
    {"Code": "BH", "name": "BAHRAIN"},
    {"Code": "BD", "name": "BANGLADESH"},
    {"Code": "BB", "name": "BARBADOS"},
    {"Code": "BY", "name": "BELARUS"},
    {"Code": "BE", "name": "BELGIUM"},
    {"Code": "BZ", "name": "BELIZE"},
    {"Code": "BJ", "name": "BENIN"},
    {"Code": "BM", "name": "BERMUDA"},
    {"Code": "BT", "name": "BHUTAN"},
    {"Code": "BO", "name": "BOLIVIA"},
    {"Code": "BA", "name": "BOSNIA AND HERZEGOVINA"},
    {"Code": "BW", "name": "BOTSWANA"},
    {"Code": "BV", "name": "BOUVET ISLAND"},
    {"Code": "BR", "name": "BRAZIL"},
    {"Code": "IO", "name": "BRITISH INDIAN OCEAN TERRITORY'Ocean Territory"},
    {"Code": "BN", "name": "BRUNEI DARUSSALAM"},
    {"Code": "BG", "name": "BULGARIA"},
    {"Code": "BF", "name": "BURKINA FASO"},
    {"Code": "BI", "name": "BURUNDI"},
    {"Code": "KH", "name": "CAMBODIA"},
    {"Code": "CM", "name": "CAMEROON"},
    {"Code": "CA", "name": "CANADA"},
    {"Code": "CV", "name": "CAPE VERDE"},
    {"Code": "KY", "name": "CAYMAN ISLANDS"},
    {"Code": "CF", "name": "CENTRAL AFRICAN REPUBLIC"},
    {"Code": "TD", "name": "CHAD"},
    {"Code": "CL", "name": "CHILE"},
    {"Code": "CN", "name": "CHINA"},
    {"Code": "CX", "name": "CHRISTMAS ISLAND"},
    {"Code": "CC", "name": "COCOS (KEELING) ISLANDS'Islands"},
    {"Code": "CO", "name": "COLOMBIA"},
    {"Code": "KM", "name": "COMOROS"},
    {"Code": "CG", "name": "CONGO"},
    {"Code": "CD", "name": "CONGO, THE DEMOCRATIC REPUBL"},
    {"Code": "CK", "name": "COOK ISLANDS"},
    {"Code": "CR", "name": "COSTA RICA"},
    {"Code": "CI", "name": "COTE D'IVOIRE"},
    {"Code": "HR", "name": "CROATIA"},
    {"Code": "CU", "name": "CUBA"},
    {"Code": "CY", "name": "CYPRUS"},
    {"Code": "CZ", "name": "CZECH REPUBLIC"},
    {"Code": "DK", "name": "DENMARK"},
    {"Code": "DJ", "name": "DJIBOUTI"},
    {"Code": "DM", "name": "DOMINICA"},
    {"Code": "DO", "name": "DOMINICAN REPUBLIC"},
    {"Code": "EC", "name": "ECUADOR"},
    {"Code": "EG", "name": "EGYPT"},
    {"Code": "SV", "name": "EL SALVADOR"},
    {"Code": "GQ", "name": "EQUATORIAL GUINEA"},
    {"Code": "ER", "name": "ERITREA"},
    {"Code": "EE", "name": "ESTONIA"},
    {"Code": "ET", "name": "ETHIOPIA"},
    {"Code": "FK", "name": "FALKLAND ISLANDS"},
    {"Code": "FO", "name": "FAROE ISLANDS"},
    {"Code": "FJ", "name": "FIJI"},
    {"Code": "FI", "name": "FINLAND"},
    {"Code": "FR", "name": "FRANCE"},
    {"Code": "GF", "name": "FRENCH GUIANA"},
    {"Code": "PF", "name": "FRENCH POLYNESIA"},
    {"Code": "TF", "name": "FRENCH SOUTHERN TERRITORIES"},
    {"Code": "GA", "name": "GABON"},
    {"Code": "GM", "name": "GAMBIA"},
    {"Code": "GE", "name": "GEORGIA"},
    {"Code": "DE", "name": "GERMANY"},
    {"Code": "GH", "name": "GHANA"},
    {"Code": "GI", "name": "GIBRALTAR"},
    {"Code": "GR", "name": "GREECE"},
    {"Code": "GL", "name": "GREENLAND"},
    {"Code": "GD", "name": "GRENADA"},
    {"Code": "GP", "name": "GUADELOUPE"},
    {"Code": "GU", "name": "GUAM"},
    {"Code": "GT", "name": "GUATEMALA"},
    {"Code": "GN", "name": "GUINEA"},
    {"Code": "GW", "name": "GUINEA-BISSAU"},
    {"Code": "GY", "name": "GUYANA"},
    {"Code": "HT", "name": "HAITI"},
    {"Code": "HM", "name": "HEARD ISLAND AND MCDONALD ISLA"},
    {"Code": "VA", "name": "HOLY SEE (VATICAN CITY STATECity State)"},
    {"Code": "HN", "name": "HONDURAS"},
    {"Code": "HK", "name": "HONG KONG"},
    {"Code": "HU", "name": "HUNGARY"},
    {"Code": "IS", "name": "ICELAND"},
    {"Code": "IN", "name": "INDIA"},
    {"Code": "ID", "name": "INDONESIA"},
    {"Code": "IR", "name": "IRAN"},
    {"Code": "IQ", "name": "IRAQ"},
    {"Code": "IE", "name": "IRELAND"},
    {"Code": "IL", "name": "ISRAEL"},
    {"Code": "IT", "name": "ITALY"},
    {"Code": "JM", "name": "JAMAICA"},
    {"Code": "JP", "name": "JAPAN"},
    {"Code": "JO", "name": "JORDAN"},
    {"Code": "KZ", "name": "KAZAKHSTAN"},
    {"Code": "KE", "name": "KENYA"},
    {"Code": "KI", "name": "KIRIBATI"},
    {"Code": "KP", "name": "KOREA"},
    {"Code": "KR", "name": "KOREA"},
    {"Code": "KW", "name": "KUWAIT"},
    {"Code": "KG", "name": "KYRGYZSTAN"},
    {"Code": "LA", "name": "LAO PEOPLE'S DEMOCRATIC REPUBLIC"},
    {"Code": "LV", "name": "LATVIA"},
    {"Code": "LB", "name": "LEBANON"},
    {"Code": "LS", "name": "LESOTHO"},
    {"Code": "LR", "name": "LIBERIA"},
    {"Code": "LY", "name": "LIBYAN ARAB JAMAHIRIYA"},
    {"Code": "LI", "name": "LIECHTENSTEIN"},
    {"Code": "LT", "name": "LITHUANIA"},
    {"Code": "LU", "name": "LUXEMBOURG"},
    {"Code": "MO", "name": "MACAO"},
    {"Code": "MK", "name": "MACEDONIA"},
    {"Code": "MG", "name": "MADAGASCAR"},
    {"Code": "MW", "name": "MALAWI"},
    {"Code": "MY", "name": "MALAYSIA"},
    {"Code": "MV", "name": "MALDIVES"},
    {"Code": "ML", "name": "MALI"},
    {"Code": "MT", "name": "MALTA"},
    {"Code": "MH", "name": "MARSHALL ISLANDS"},
    {"Code": "MQ", "name": "MARTINIQUE"},
    {"Code": "MR", "name": "MAURITANIA"},
    {"Code": "MU", "name": "MAURITIUS"},
    {"Code": "YT", "name": "MAYOTTE"},
    {"Code": "MX", "name": "MEXICO"},
    {"Code": "FM", "name": "MICRONESIA"},
    {"Code": "MC", "name": "MONACO"},
    {"Code": "MN", "name": "MONGOLIA"},
    {"Code": "MS", "name": "MONTSERRAT"},
    {"Code": "MA", "name": "MOROCCO"},
    {"Code": "MZ", "name": "MOZAMBIQUE"},
    {"Code": "MM", "name": "MYANMAR"},
    {"Code": "NA", "name": "NAMIBIA"},
    {"Code": "NR", "name": "NAURU"},
    {"Code": "NP", "name": "NEPAL"},
    {"Code": "NL", "name": "NETHERLANDS"},
    {"Code": "AN", "name": "NETHERLANDS ANTILLES"},
    {"Code": "NC", "name": "NEW CALEDONIA"},
    {"Code": "NZ", "name": "NEW ZEALAND"},
    {"Code": "NI", "name": "NICARAGUA"},
    {"Code": "NE", "name": "NIGER"},
    {"Code": "NG", "name": "NIGERIA"},
    {"Code": "NU", "name": "NIUE"},
    {"Code": "NF", "name": "NORFOLK ISLAND"},
    {"Code": "MP", "name": "NORTHERN MARIANA ISLANDS"},
    {"Code": "NO", "name": "NORWAY"},
    {"Code": "OM", "name": "OMAN"},
    {"Code": "PK", "name": "PAKISTAN"},
    {"Code": "PW", "name": "PALAU"},
    {"Code": "PS", "name": "PALESTINIAN TERRITORY"},
    {"Code": "PA", "name": "PANAMA"},
    {"Code": "PG", "name": "PAPUA NEW GUINEA"},
    {"Code": "PY", "name": "PARAGUAY"},
    {"Code": "PE", "name": "PERU"},
    {"Code": "PH", "name": "PHILIPPINES"},
    {"Code": "PN", "name": "PITCAIRN"},
    {"Code": "PL", "name": "POLAND"},
    {"Code": "PT", "name": "PORTUGAL"},
    {"Code": "PR", "name": "PUERTO RICO"},
    {"Code": "QA", "name": "QATAR"},
    {"Code": "RE", "name": "REUNION"},
    {"Code": "RO", "name": "ROMANIA"},
    {"Code": "RU", "name": "RUSSIAN FEDERATION"},
    {"Code": "RW", "name": "RWANDA"},
    {"Code": "SH", "name": "SAINT HELENA"},
    {"Code": "KN", "name": "SAINT KITTS AND NEVIS'Nevis"},
    {"Code": "LC", "name": "SAINT LUCIA"},
    {"Code": "PM", "name": "SAINT PIERRE AND MIQUELON"},
    {"Code": "VC", "name": "SAINT VINCENT AND THE GRENADINE"},
    {"Code": "WS", "name": "SAMOA"},
    {"Code": "SM", "name": "SAN MARINO"},
    {"Code": "ST", "name": "SAO TOME AND PRINCIPE"},
    {"Code": "SA", "name": "SAUDI ARABIA"},
    {"Code": "SN", "name": "SENEGAL"},
    {"Code": "CS", "name": "SERBIA AND MONTENEGRO"},
    {"Code": "SC", "name": "SEYCHELLES"},
    {"Code": "SL", "name": "SIERRA LEONE"},
    {"Code": "SG", "name": "SINGAPORE"},
    {"Code": "SK", "name": "SLOVAKIA"},
    {"Code": "SI", "name": "SLOVENIA"},
    {"Code": "SB", "name": "SOLOMON ISLANDS"},
    {"Code": "SO", "name": "SOMALIA"},
    {"Code": "ZA", "name": "SOUTH AFRICA"},
    {"Code": "GS", "name": "SOUTH GEORGIA"},
    {"Code": "ES", "name": "SPAIN"},
    {"Code": "LK", "name": "SRI LANKA"},
    {"Code": "SD", "name": "SUDAN"},
    {"Code": "SR", "name": "SURINAME"},
    {"Code": "SJ", "name": "SVALBARD AND JAN MAYEN"},
    {"Code": "SZ", "name": "SWAZILAND"},
    {"Code": "SE", "name": "SWEDEN"},
    {"Code": "CH", "name": "SWITZERLAND"},
    {"Code": "SY", "name": "SYRIAN ARAB REPUBLIC'"},
    {"Code": "TW", "name": "TAIWAN, PROVINCE OF CHIN"},
    {"Code": "TJ", "name": "TAJIKISTAN"},
    {"Code": "TZ", "name": "TANZANIA, UNITED REPUBLIC OFRepublic of"},
    {"Code": "TH", "name": "THAILAND"},
    {"Code": "TL", "name": "TIMOR-LESTE"},
    {"Code": "TG", "name": "TOGO"},
    {"Code": "TK", "name": "TOKELAU"},
    {"Code": "TO", "name": "TONGA"},
    {"Code": "TT", "name": "TRINIDAD AND TOBAGO"},
    {"Code": "TN", "name": "TUNISIA"},
    {"Code": "TR", "name": "TURKEY"},
    {"Code": "TM", "name": "TURKMENISTAN"},
    {"Code": "TC", "name": "TURKS AND CAICOS ISLANDS'Islands"},
    {"Code": "TV", "name": "TUVALU"},
    {"Code": "UG", "name": "UGANDA"},
    {"Code": "UA", "name": "UKRAINE"},
    {"Code": "AE", "name": "UNITED ARAB EMIRATES"},
    {"Code": "GB", "name": "UNITED KINGDOM"},
    {"Code": "US", "name": "UNITED STATES"},
    {"Code": "UM", "name": "UNITED STATES MINOR OUTLYING ISLANDS"},
    {"Code": "UY", "name": "URUGUAY"},
    {"Code": "UZ", "name": "UZBEKISTAN"},
    {"Code": "VU", "name": "VANUATU"},
    {"Code": "VE", "name": "VENEZUELA"},
    {"Code": "VN", "name": "VIET NAM"},
    {"Code": "VG", "name": "VIRGIN ISLANDS"},
    {"Code": "VI", "name": "VIRGIN ISLANDS"},
    {"Code": "WF", "name": "WALLIS AND FUTUNA"},
    {"Code": "EH", "name": "WESTERN SAHARA"},
    {"Code": "YE", "name": "YEMEN"},
    {"Code": "ZM", "name": "ZAMBIA"},
    {"Code": "ZW", "name": "ZIMBABWE"},
    {"Code": "RS", "name": "SERBIA"},
    {"Code": "AP", "name": "ASIA PACIFIC REGIO"},
    {"Code": "ME", "name": "MONTENEGRO"},
    {"Code": "AX", "name": "ALAND ISLANDS"},
    {"Code": "BQ", "name": "BONAIR"},
    {"Code": "CW", "name": "CURACAO"},
    {"Code": "GG", "name": "GUERNSEY"},
    {"Code": "IM", "name": "ISLE OF MAN"},
    {"Code": "JE", "name": "JERSEY"},
    {"Code": "XK", "name": "KOSOVO"},
    {"Code": "BL", "name": "SAINT BARTHELEMY"},
    {"Code": "MF", "name": "SAINT MARTIN"},
    {"Code": "SX", "name": "SINT MAARTEN"},
    {"Code": "SS", "name": "SOUTH SUDAN"},
  ]
}
