export class countryList {
  public static countries = [
    {"Code": "AF", "Name": "Afghanistan"},
    {"Code": "AL", "Name": "Albania"},
    {"Code": "DZ", "Name": "Algeria"},
    {"Code": "AS", "Name": "American samoa"},
    {"Code": "AD", "Name": "Andorra"},
    {"Code": "AO", "Name": "Angola"},
    {"Code": "AI", "Name": "Anguilla"},
    {"Code": "AQ", "Name": "Antarctica"},
    {"Code": "AG", "Name": "Antigua and barbuda"},
    {"Code": "AR", "Name": "Argentina"},
    {"Code": "AM", "Name": "Armenia"},
    {"Code": "AW", "Name": "Aruba"},
    {"Code": "AU", "Name": "Australia"},
    {"Code": "AT", "Name": "Austria"},
    {"Code": "AZ", "Name": "Azerbaijan"},
    {"Code": "BS", "Name": "Bahamas"},
    {"Code": "BH", "Name": "Bahrain"},
    {"Code": "BD", "Name": "Bangladesh"},
    {"Code": "BB", "Name": "Barbados"},
    {"Code": "BY", "Name": "Belarus"},
    {"Code": "BE", "Name": "Belgium"},
    {"Code": "BZ", "Name": "Belize"},
    {"Code": "BJ", "Name": "Benin"},
    {"Code": "BM", "Name": "Bermuda"},
    {"Code": "BT", "Name": "Bhutan"},
    {"Code": "BO", "Name": "Bolivia"},
    {"Code": "BA", "Name": "Bosnia and herzegovina"},
    {"Code": "BW", "Name": "Botswana"},
    {"Code": "BV", "Name": "Bouvet island"},
    {"Code": "BR", "Name": "Brazil"},
    {"Code": "IO", "Name": "British indian ocean territory"},
    {"Code": "BN", "Name": "Brunei darussalam"},
    {"Code": "BG", "Name": "Bulgaria"},
    {"Code": "BF", "Name": "Burkina faso"},
    {"Code": "BI", "Name": "Burundi"},
    {"Code": "KH", "Name": "Cambodia"},
    {"Code": "CM", "Name": "Cameroon"},
    {"Code": "CA", "Name": "Canada"},
    {"Code": "CV", "Name": "Cape verde"},
    {"Code": "KY", "Name": "Cayman islands"},
    {"Code": "CF", "Name": "Central african republic"},
    {"Code": "TD", "Name": "Chad"},
    {"Code": "CL", "Name": "Chile"},
    {"Code": "CN", "Name": "China"},
    {"Code": "CX", "Name": "Christmas island"},
    {"Code": "CC", "Name": "Cocos islands"},
    {"Code": "CO", "Name": "Colombia"},
    {"Code": "KM", "Name": "Comoros"},
    {"Code": "CG", "Name": "Congo"},
    {"Code": "CD", "Name": "Congo the democratic republ"},
    {"Code": "CK", "Name": "Cook islands"},
    {"Code": "CR", "Name": "Costa rica"},
    {"Code": "CI", "Name": "Cote divoire"},
    {"Code": "HR", "Name": "Croatia"},
    {"Code": "CU", "Name": "Cuba"},
    {"Code": "CY", "Name": "Cyprus"},
    {"Code": "CZ", "Name": "Czech republic"},
    {"Code": "DK", "Name": "Denmark"},
    {"Code": "DJ", "Name": "Djibouti"},
    {"Code": "DM", "Name": "Dominica"},
    {"Code": "DO", "Name": "Dominican republic"},
    {"Code": "EC", "Name": "Ecuador"},
    {"Code": "EG", "Name": "Egypt"},
    {"Code": "SV", "Name": "El salvador"},
    {"Code": "GQ", "Name": "Equatorial guinea"},
    {"Code": "ER", "Name": "Eritrea"},
    {"Code": "EE", "Name": "Estonia"},
    {"Code": "ET", "Name": "Ethiopia"},
    {"Code": "FK", "Name": "Falkland islands"},
    {"Code": "FO", "Name": "Faroe islands"},
    {"Code": "FJ", "Name": "Fiji"},
    {"Code": "FI", "Name": "Finland"},
    {"Code": "FR", "Name": "France"},
    {"Code": "GF", "Name": "French guiana"},
    {"Code": "PF", "Name": "French polynesia"},
    {"Code": "TF", "Name": "French southern territories"},
    {"Code": "GA", "Name": "Gabon"},
    {"Code": "GM", "Name": "Gambia"},
    {"Code": "GE", "Name": "Georgia"},
    {"Code": "DE", "Name": "Germany"},
    {"Code": "GH", "Name": "Ghana"},
    {"Code": "GI", "Name": "Gibraltar"},
    {"Code": "GR", "Name": "Greece"},
    {"Code": "GL", "Name": "Greenland"},
    {"Code": "GD", "Name": "Grenada"},
    {"Code": "GP", "Name": "Guadeloupe"},
    {"Code": "GU", "Name": "Guam"},
    {"Code": "GT", "Name": "Guatemala"},
    {"Code": "GN", "Name": "Guinea"},
    {"Code": "GW", "Name": "Guinea bissau"},
    {"Code": "GY", "Name": "Guyana"},
    {"Code": "HT", "Name": "Haiti"},
    {"Code": "HM", "Name": "Heard island and mcdonald isla"},
    {"Code": "VA", "Name": "Holy see vatican city"},
    {"Code": "HN", "Name": "Honduras"},
    {"Code": "HK", "Name": "Hong kong"},
    {"Code": "HU", "Name": "Hungary"},
    {"Code": "IS", "Name": "Iceland"},
    {"Code": "IN", "Name": "India"},
    {"Code": "ID", "Name": "Indonesia"},
    {"Code": "IR", "Name": "Iran"},
    {"Code": "IQ", "Name": "Iraq"},
    {"Code": "IE", "Name": "Ireland"},
    {"Code": "IL", "Name": "Israel"},
    {"Code": "IT", "Name": "Italy"},
    {"Code": "JM", "Name": "Jamaica"},
    {"Code": "JP", "Name": "Japan"},
    {"Code": "JO", "Name": "Jordan"},
    {"Code": "KZ", "Name": "Kazakhstan"},
    {"Code": "KE", "Name": "Kenya"},
    {"Code": "KI", "Name": "Kiribati"},
    {"Code": "KR", "Name": "Korea"},
    {"Code": "KW", "Name": "Kuwait"},
    {"Code": "KG", "Name": "Kyrgyzstan"},
    {"Code": "LA", "Name": "Lao peoples democratic republic"},
    {"Code": "LV", "Name": "Latvia"},
    {"Code": "LB", "Name": "Lebanon"},
    {"Code": "LS", "Name": "Lesotho"},
    {"Code": "LR", "Name": "Liberia"},
    {"Code": "LY", "Name": "Libyan arab jamahiriya"},
    {"Code": "LI", "Name": "Liechtenstein"},
    {"Code": "LT", "Name": "Lithuania"},
    {"Code": "LU", "Name": "Luxembourg"},
    {"Code": "MO", "Name": "Macao"},
    {"Code": "MK", "Name": "Macedonia"},
    {"Code": "MG", "Name": "Madagascar"},
    {"Code": "MW", "Name": "Malawi"},
    {"Code": "MY", "Name": "Malaysia"},
    {"Code": "MV", "Name": "Maldives"},
    {"Code": "ML", "Name": "Mali"},
    {"Code": "MT", "Name": "Malta"},
    {"Code": "MH", "Name": "Marshall islands"},
    {"Code": "MQ", "Name": "Martinique"},
    {"Code": "MR", "Name": "Mauritania"},
    {"Code": "MU", "Name": "Mauritius"},
    {"Code": "YT", "Name": "Mayotte"},
    {"Code": "MX", "Name": "Mexico"},
    {"Code": "FM", "Name": "Micronesia"},
    {"Code": "MC", "Name": "Monaco"},
    {"Code": "MN", "Name": "Mongolia"},
    {"Code": "MS", "Name": "Montserrat"},
    {"Code": "MA", "Name": "Morocco"},
    {"Code": "MZ", "Name": "Mozambique"},
    {"Code": "MM", "Name": "Myanmar"},
    {"Code": "NA", "Name": "Namibia"},
    {"Code": "NR", "Name": "Nauru"},
    {"Code": "NP", "Name": "Nepal"},
    {"Code": "NL", "Name": "Netherlands"},
    {"Code": "AN", "Name": "Netherlands antilles"},
    {"Code": "NC", "Name": "New caledonia"},
    {"Code": "NZ", "Name": "New zealand"},
    {"Code": "NI", "Name": "Nicaragua"},
    {"Code": "NE", "Name": "Niger"},
    {"Code": "NG", "Name": "Nigeria"},
    {"Code": "NU", "Name": "Niue"},
    {"Code": "NF", "Name": "Norfolk island"},
    {"Code": "MP", "Name": "Northern mariana islands"},
    {"Code": "NO", "Name": "Norway"},
    {"Code": "OM", "Name": "Oman"},
    {"Code": "PK", "Name": "Pakistan"},
    {"Code": "PW", "Name": "Palau"},
    {"Code": "PS", "Name": "Palestinian territory"},
    {"Code": "PA", "Name": "Panama"},
    {"Code": "PG", "Name": "Papua new guinea"},
    {"Code": "PY", "Name": "Paraguay"},
    {"Code": "PE", "Name": "Peru"},
    {"Code": "PH", "Name": "Philippines"},
    {"Code": "PN", "Name": "Pitcairn"},
    {"Code": "PL", "Name": "Poland"},
    {"Code": "PT", "Name": "Portugal"},
    {"Code": "PR", "Name": "Puerto rico"},
    {"Code": "QA", "Name": "Qatar"},
    {"Code": "RE", "Name": "Reunion"},
    {"Code": "RO", "Name": "Romania"},
    {"Code": "RU", "Name": "Russian federation"},
    {"Code": "RW", "Name": "Rwanda"},
    {"Code": "SH", "Name": "Saint helena"},
    {"Code": "KN", "Name": "Saint kitts and nevis"},
    {"Code": "LC", "Name": "Saint lucia"},
    {"Code": "PM", "Name": "Saint pierre and miquelon"},
    {"Code": "VC", "Name": "Saint vincent and the grenadine"},
    {"Code": "WS", "Name": "Samoa"},
    {"Code": "SM", "Name": "San marino"},
    {"Code": "ST", "Name": "Sao tome and principe"},
    {"Code": "SA", "Name": "Saudi arabia"},
    {"Code": "SN", "Name": "Senegal"},
    {"Code": "CS", "Name": "Serbia and montenegro"},
    {"Code": "SC", "Name": "Seychelles"},
    {"Code": "SL", "Name": "Sierra leone"},
    {"Code": "SG", "Name": "Singapore"},
    {"Code": "SK", "Name": "Slovakia"},
    {"Code": "SI", "Name": "Slovenia"},
    {"Code": "SB", "Name": "Solomon islands"},
    {"Code": "SO", "Name": "Somalia"},
    {"Code": "ZA", "Name": "South africa"},
    {"Code": "GS", "Name": "South georgia"},
    {"Code": "ES", "Name": "Spain"},
    {"Code": "LK", "Name": "Sri lanka"},
    {"Code": "SD", "Name": "Sudan"},
    {"Code": "SR", "Name": "Suriname"},
    {"Code": "SJ", "Name": "Svalbard and jan mayen"},
    {"Code": "SZ", "Name": "Swaziland"},
    {"Code": "SE", "Name": "Sweden"},
    {"Code": "CH", "Name": "Switzerland"},
    {"Code": "SY", "Name": "Syrian arab republic"},
    {"Code": "TW", "Name": "Taiwan province of china"},
    {"Code": "TJ", "Name": "Tajikistan"},
    {"Code": "TZ", "Name": "Tanzania united republic"},
    {"Code": "TH", "Name": "Thailand"},
    {"Code": "TL", "Name": "Timor leste"},
    {"Code": "TG", "Name": "Togo"},
    {"Code": "TK", "Name": "Tokelau"},
    {"Code": "TO", "Name": "Tonga"},
    {"Code": "TT", "Name": "Trinidad and tobago"},
    {"Code": "TN", "Name": "Tunisia"},
    {"Code": "TR", "Name": "Turkey"},
    {"Code": "TM", "Name": "Turkmenistan"},
    {"Code": "TC", "Name": "Turks and caicos islands"},
    {"Code": "TV", "Name": "Tuvalu"},
    {"Code": "UG", "Name": "Uganda"},
    {"Code": "UA", "Name": "Ukraine"},
    {"Code": "AE", "Name": "United arab emirates"},
    {"Code": "GB", "Name": "United kingdom"},
    {"Code": "US", "Name": "United states"},
    {"Code": "UM", "Name": "United states minor outlying islands"},
    {"Code": "UY", "Name": "Uruguay"},
    {"Code": "UZ", "Name": "Uzbekistan"},
    {"Code": "VU", "Name": "Vanuatu"},
    {"Code": "VE", "Name": "Venezuela"},
    {"Code": "VN", "Name": "Viet nam"},
    {"Code": "VG", "Name": "Virgin islands"},
    {"Code": "WF", "Name": "Wallis and futuna"},
    {"Code": "EH", "Name": "Western sahara"},
    {"Code": "YE", "Name": "Yemen"},
    {"Code": "ZM", "Name": "Zambia"},
    {"Code": "ZW", "Name": "Zimbabwe"},
    {"Code": "RS", "Name": "Serbia"},
    {"Code": "AP", "Name": "Asia pacific regio"},
    {"Code": "ME", "Name": "Montenegro"},
    {"Code": "AX", "Name": "Aland islands"},
    {"Code": "BQ", "Name": "Bonair"},
    {"Code": "CW", "Name": "Curacao"},
    {"Code": "GG", "Name": "Guernsey"},
    {"Code": "IM", "Name": "Isle of man"},
    {"Code": "JE", "Name": "Jersey"},
    {"Code": "XK", "Name": "Kosovo"},
    {"Code": "BL", "Name": "Saint barthelemy"},
    {"Code": "MF", "Name": "Saint martin"},
    {"Code": "SX", "Name": "Sint maarten"},
    {"Code": "SS", "Name": "South sudan"},
  ]
}
