export class countryList {
  public static countries = [
    {"Code": "AF", "Name": "AFGHANISTAN"},
    {"Code": "AL", "Name": "ALBANIA"},
    {"Code": "DZ", "Name": "ALGERIA"},
    {"Code": "AS", "Name": "AMERICAN SAMOA"},
    {"Code": "AD", "Name": "ANDORRA"},
    {"Code": "AO", "Name": "ANGOLA"},
    {"Code": "AI", "Name": "ANGUILLA"},
    {"Code": "AQ", "Name": "ANTARCTICA"},
    {"Code": "AG", "Name": "ANTIGUA AND BARBUDA"},
    {"Code": "AR", "Name": "ARGENTINA"},
    {"Code": "AM", "Name": "ARMENIA"},
    {"Code": "AW", "Name": "ARUBA"},
    {"Code": "AU", "Name": "AUSTRALIA"},
    {"Code": "AT", "Name": "AUSTRIA"},
    {"Code": "AZ", "Name": "AZERBAIJAN"},
    {"Code": "BS", "Name": "BAHAMAS"},
    {"Code": "BH", "Name": "BAHRAIN"},
    {"Code": "BD", "Name": "BANGLADESH"},
    {"Code": "BB", "Name": "BARBADOS"},
    {"Code": "BY", "Name": "BELARUS"},
    {"Code": "BE", "Name": "BELGIUM"},
    {"Code": "BZ", "Name": "BELIZE"},
    {"Code": "BJ", "Name": "BENIN"},
    {"Code": "BM", "Name": "BERMUDA"},
    {"Code": "BT", "Name": "BHUTAN"},
    {"Code": "BO", "Name": "BOLIVIA"},
    {"Code": "BA", "Name": "BOSNIA AND HERZEGOVINA"},
    {"Code": "BW", "Name": "BOTSWANA"},
    {"Code": "BV", "Name": "BOUVET ISLAND"},
    {"Code": "BR", "Name": "BRAZIL"},
    {"Code": "IO", "Name": "BRITISH INDIAN OCEAN TERRITORY"},
    {"Code": "BN", "Name": "BRUNEI DARUSSALAM"},
    {"Code": "BG", "Name": "BULGARIA"},
    {"Code": "BF", "Name": "BURKINA FASO"},
    {"Code": "BI", "Name": "BURUNDI"},
    {"Code": "KH", "Name": "CAMBODIA"},
    {"Code": "CM", "Name": "CAMEROON"},
    {"Code": "CA", "Name": "CANADA"},
    {"Code": "CV", "Name": "CAPE VERDE"},
    {"Code": "KY", "Name": "CAYMAN ISLANDS"},
    {"Code": "CF", "Name": "CENTRAL AFRICAN REPUBLIC"},
    {"Code": "TD", "Name": "CHAD"},
    {"Code": "CL", "Name": "CHILE"},
    {"Code": "CN", "Name": "CHINA"},
    {"Code": "CX", "Name": "CHRISTMAS ISLAND"},
    {"Code": "CC", "Name": "COCOS ISLANDS"},
    {"Code": "CO", "Name": "COLOMBIA"},
    {"Code": "KM", "Name": "COMOROS"},
    {"Code": "CG", "Name": "CONGO"},
    {"Code": "CD", "Name": "CONGO THE DEMOCRATIC REPUBL"},
    {"Code": "CK", "Name": "COOK ISLANDS"},
    {"Code": "CR", "Name": "COSTA RICA"},
    {"Code": "CI", "Name": "COTE DIVOIRE"},
    {"Code": "HR", "Name": "CROATIA"},
    {"Code": "CU", "Name": "CUBA"},
    {"Code": "CY", "Name": "CYPRUS"},
    {"Code": "CZ", "Name": "CZECH REPUBLIC"},
    {"Code": "DK", "Name": "DENMARK"},
    {"Code": "DJ", "Name": "DJIBOUTI"},
    {"Code": "DM", "Name": "DOMINICA"},
    {"Code": "DO", "Name": "DOMINICAN REPUBLIC"},
    {"Code": "EC", "Name": "ECUADOR"},
    {"Code": "EG", "Name": "EGYPT"},
    {"Code": "SV", "Name": "EL SALVADOR"},
    {"Code": "GQ", "Name": "EQUATORIAL GUINEA"},
    {"Code": "ER", "Name": "ERITREA"},
    {"Code": "EE", "Name": "ESTONIA"},
    {"Code": "ET", "Name": "ETHIOPIA"},
    {"Code": "FK", "Name": "FALKLAND ISLANDS"},
    {"Code": "FO", "Name": "FAROE ISLANDS"},
    {"Code": "FJ", "Name": "FIJI"},
    {"Code": "FI", "Name": "FINLAND"},
    {"Code": "FR", "Name": "FRANCE"},
    {"Code": "GF", "Name": "FRENCH GUIANA"},
    {"Code": "PF", "Name": "FRENCH POLYNESIA"},
    {"Code": "TF", "Name": "FRENCH SOUTHERN TERRITORIES"},
    {"Code": "GA", "Name": "GABON"},
    {"Code": "GM", "Name": "GAMBIA"},
    {"Code": "GE", "Name": "GEORGIA"},
    {"Code": "DE", "Name": "GERMANY"},
    {"Code": "GH", "Name": "GHANA"},
    {"Code": "GI", "Name": "GIBRALTAR"},
    {"Code": "GR", "Name": "GREECE"},
    {"Code": "GL", "Name": "GREENLAND"},
    {"Code": "GD", "Name": "GRENADA"},
    {"Code": "GP", "Name": "GUADELOUPE"},
    {"Code": "GU", "Name": "GUAM"},
    {"Code": "GT", "Name": "GUATEMALA"},
    {"Code": "GN", "Name": "GUINEA"},
    {"Code": "GW", "Name": "GUINEA BISSAU"},
    {"Code": "GY", "Name": "GUYANA"},
    {"Code": "HT", "Name": "HAITI"},
    {"Code": "HM", "Name": "HEARD ISLAND AND MCDONALD ISLA"},
    {"Code": "VA", "Name": "HOLY SEE VATICAN CITY"},
    {"Code": "HN", "Name": "HONDURAS"},
    {"Code": "HK", "Name": "HONG KONG"},
    {"Code": "HU", "Name": "HUNGARY"},
    {"Code": "IS", "Name": "ICELAND"},
    {"Code": "IN", "Name": "INDIA"},
    {"Code": "ID", "Name": "INDONESIA"},
    {"Code": "IR", "Name": "IRAN"},
    {"Code": "IQ", "Name": "IRAQ"},
    {"Code": "IE", "Name": "IRELAND"},
    {"Code": "IL", "Name": "ISRAEL"},
    {"Code": "IT", "Name": "ITALY"},
    {"Code": "JM", "Name": "JAMAICA"},
    {"Code": "JP", "Name": "JAPAN"},
    {"Code": "JO", "Name": "JORDAN"},
    {"Code": "KZ", "Name": "KAZAKHSTAN"},
    {"Code": "KE", "Name": "KENYA"},
    {"Code": "KI", "Name": "KIRIBATI"},
    {"Code": "KR", "Name": "KOREA"},
    {"Code": "KW", "Name": "KUWAIT"},
    {"Code": "KG", "Name": "KYRGYZSTAN"},
    {"Code": "LA", "Name": "LAO PEOPLES DEMOCRATIC REPUBLIC"},
    {"Code": "LV", "Name": "LATVIA"},
    {"Code": "LB", "Name": "LEBANON"},
    {"Code": "LS", "Name": "LESOTHO"},
    {"Code": "LR", "Name": "LIBERIA"},
    {"Code": "LY", "Name": "LIBYAN ARAB JAMAHIRIYA"},
    {"Code": "LI", "Name": "LIECHTENSTEIN"},
    {"Code": "LT", "Name": "LITHUANIA"},
    {"Code": "LU", "Name": "LUXEMBOURG"},
    {"Code": "MO", "Name": "MACAO"},
    {"Code": "MK", "Name": "MACEDONIA"},
    {"Code": "MG", "Name": "MADAGASCAR"},
    {"Code": "MW", "Name": "MALAWI"},
    {"Code": "MY", "Name": "MALAYSIA"},
    {"Code": "MV", "Name": "MALDIVES"},
    {"Code": "ML", "Name": "MALI"},
    {"Code": "MT", "Name": "MALTA"},
    {"Code": "MH", "Name": "MARSHALL ISLANDS"},
    {"Code": "MQ", "Name": "MARTINIQUE"},
    {"Code": "MR", "Name": "MAURITANIA"},
    {"Code": "MU", "Name": "MAURITIUS"},
    {"Code": "YT", "Name": "MAYOTTE"},
    {"Code": "MX", "Name": "MEXICO"},
    {"Code": "FM", "Name": "MICRONESIA"},
    {"Code": "MC", "Name": "MONACO"},
    {"Code": "MN", "Name": "MONGOLIA"},
    {"Code": "MS", "Name": "MONTSERRAT"},
    {"Code": "MA", "Name": "MOROCCO"},
    {"Code": "MZ", "Name": "MOZAMBIQUE"},
    {"Code": "MM", "Name": "MYANMAR"},
    {"Code": "NA", "Name": "NAMIBIA"},
    {"Code": "NR", "Name": "NAURU"},
    {"Code": "NP", "Name": "NEPAL"},
    {"Code": "NL", "Name": "NETHERLANDS"},
    {"Code": "AN", "Name": "NETHERLANDS ANTILLES"},
    {"Code": "NC", "Name": "NEW CALEDONIA"},
    {"Code": "NZ", "Name": "NEW ZEALAND"},
    {"Code": "NI", "Name": "NICARAGUA"},
    {"Code": "NE", "Name": "NIGER"},
    {"Code": "NG", "Name": "NIGERIA"},
    {"Code": "NU", "Name": "NIUE"},
    {"Code": "NF", "Name": "NORFOLK ISLAND"},
    {"Code": "MP", "Name": "NORTHERN MARIANA ISLANDS"},
    {"Code": "NO", "Name": "NORWAY"},
    {"Code": "OM", "Name": "OMAN"},
    {"Code": "PK", "Name": "PAKISTAN"},
    {"Code": "PW", "Name": "PALAU"},
    {"Code": "PS", "Name": "PALESTINIAN TERRITORY"},
    {"Code": "PA", "Name": "PANAMA"},
    {"Code": "PG", "Name": "PAPUA NEW GUINEA"},
    {"Code": "PY", "Name": "PARAGUAY"},
    {"Code": "PE", "Name": "PERU"},
    {"Code": "PH", "Name": "PHILIPPINES"},
    {"Code": "PN", "Name": "PITCAIRN"},
    {"Code": "PL", "Name": "POLAND"},
    {"Code": "PT", "Name": "PORTUGAL"},
    {"Code": "PR", "Name": "PUERTO RICO"},
    {"Code": "QA", "Name": "QATAR"},
    {"Code": "RE", "Name": "REUNION"},
    {"Code": "RO", "Name": "ROMANIA"},
    {"Code": "RU", "Name": "RUSSIAN FEDERATION"},
    {"Code": "RW", "Name": "RWANDA"},
    {"Code": "SH", "Name": "SAINT HELENA"},
    {"Code": "KN", "Name": "SAINT KITTS AND NEVIS"},
    {"Code": "LC", "Name": "SAINT LUCIA"},
    {"Code": "PM", "Name": "SAINT PIERRE AND MIQUELON"},
    {"Code": "VC", "Name": "SAINT VINCENT AND THE GRENADINE"},
    {"Code": "WS", "Name": "SAMOA"},
    {"Code": "SM", "Name": "SAN MARINO"},
    {"Code": "ST", "Name": "SAO TOME AND PRINCIPE"},
    {"Code": "SA", "Name": "SAUDI ARABIA"},
    {"Code": "SN", "Name": "SENEGAL"},
    {"Code": "CS", "Name": "SERBIA AND MONTENEGRO"},
    {"Code": "SC", "Name": "SEYCHELLES"},
    {"Code": "SL", "Name": "SIERRA LEONE"},
    {"Code": "SG", "Name": "SINGAPORE"},
    {"Code": "SK", "Name": "SLOVAKIA"},
    {"Code": "SI", "Name": "SLOVENIA"},
    {"Code": "SB", "Name": "SOLOMON ISLANDS"},
    {"Code": "SO", "Name": "SOMALIA"},
    {"Code": "ZA", "Name": "SOUTH AFRICA"},
    {"Code": "GS", "Name": "SOUTH GEORGIA"},
    {"Code": "ES", "Name": "SPAIN"},
    {"Code": "LK", "Name": "SRI LANKA"},
    {"Code": "SD", "Name": "SUDAN"},
    {"Code": "SR", "Name": "SURINAME"},
    {"Code": "SJ", "Name": "SVALBARD AND JAN MAYEN"},
    {"Code": "SZ", "Name": "SWAZILAND"},
    {"Code": "SE", "Name": "SWEDEN"},
    {"Code": "CH", "Name": "SWITZERLAND"},
    {"Code": "SY", "Name": "SYRIAN ARAB REPUBLIC"},
    {"Code": "TW", "Name": "TAIWAN PROVINCE OF CHINA"},
    {"Code": "TJ", "Name": "TAJIKISTAN"},
    {"Code": "TZ", "Name": "TANZANIA UNITED REPUBLIC"},
    {"Code": "TH", "Name": "THAILAND"},
    {"Code": "TL", "Name": "TIMOR LESTE"},
    {"Code": "TG", "Name": "TOGO"},
    {"Code": "TK", "Name": "TOKELAU"},
    {"Code": "TO", "Name": "TONGA"},
    {"Code": "TT", "Name": "TRINIDAD AND TOBAGO"},
    {"Code": "TN", "Name": "TUNISIA"},
    {"Code": "TR", "Name": "TURKEY"},
    {"Code": "TM", "Name": "TURKMENISTAN"},
    {"Code": "TC", "Name": "TURKS AND CAICOS ISLANDS"},
    {"Code": "TV", "Name": "TUVALU"},
    {"Code": "UG", "Name": "UGANDA"},
    {"Code": "UA", "Name": "UKRAINE"},
    {"Code": "AE", "Name": "UNITED ARAB EMIRATES"},
    {"Code": "GB", "Name": "UNITED KINGDOM"},
    {"Code": "US", "Name": "UNITED STATES"},
    {"Code": "UM", "Name": "UNITED STATES MINOR OUTLYING ISLANDS"},
    {"Code": "UY", "Name": "URUGUAY"},
    {"Code": "UZ", "Name": "UZBEKISTAN"},
    {"Code": "VU", "Name": "VANUATU"},
    {"Code": "VE", "Name": "VENEZUELA"},
    {"Code": "VN", "Name": "VIET NAM"},
    {"Code": "VG", "Name": "VIRGIN ISLANDS"},
    {"Code": "WF", "Name": "WALLIS AND FUTUNA"},
    {"Code": "EH", "Name": "WESTERN SAHARA"},
    {"Code": "YE", "Name": "YEMEN"},
    {"Code": "ZM", "Name": "ZAMBIA"},
    {"Code": "ZW", "Name": "ZIMBABWE"},
    {"Code": "RS", "Name": "SERBIA"},
    {"Code": "AP", "Name": "ASIA PACIFIC REGIO"},
    {"Code": "ME", "Name": "MONTENEGRO"},
    {"Code": "AX", "Name": "ALAND ISLANDS"},
    {"Code": "BQ", "Name": "BONAIR"},
    {"Code": "CW", "Name": "CURACAO"},
    {"Code": "GG", "Name": "GUERNSEY"},
    {"Code": "IM", "Name": "ISLE OF MAN"},
    {"Code": "JE", "Name": "JERSEY"},
    {"Code": "XK", "Name": "KOSOVO"},
    {"Code": "BL", "Name": "SAINT BARTHELEMY"},
    {"Code": "MF", "Name": "SAINT MARTIN"},
    {"Code": "SX", "Name": "SINT MAARTEN"},
    {"Code": "SS", "Name": "SOUTH SUDAN"},
  ]
}
