export class FRcountrylist {
    public static FRcountrylist = [
      {"Code": "AF", "name": "AFGHANISTAN"},
      {"Code": "AL", "name": "ALBANIE"},
      {"Code": "DZ", "name": "ALGÉRIE"},
      {"Code": "AS", "name": "SAMOA AMÉRICAINE"},
      {"Code": "AD", "name": "ANDORRE"},
      {"Code": "AO", "name": "ANGOLA"},
      {"Code": "AI", "name": "ANGUILLA"},
      {"Code": "AQ", "name": "ANTARCTICA"},
      {"Code": "AG", "name": "ANTIGUA ET BARBUDA"},
      {"Code": "AR", "name": "ARGENTINE"},
      {"Code": "AM", "name": "ARMENIA"},
      {"Code": "AW", "name": "ARUBA"},
      {"Code": "AU", "name": "AUSTRALIE"},
      {"Code": "AT", "name": "AUTRICHE"},
      {"Code": "AZ", "name": "AZERBAIJAN"},
      {"Code": "BS", "name": "BAHAMAS"},
      {"Code": "BH", "name": "BAHRAIN"},
      {"Code": "BD", "name": "BANGLADESH"},
      {"Code": "BB", "name": "BARBADOS"},
      {"Code": "BY", "name": "BELARUS"},
      {"Code": "BE", "name": "BELGIQUE"},
      {"Code": "BZ", "name": "BELIZE"},
      {"Code": "BJ", "name": "BENIN"},
      {"Code": "BM", "name": "BERMUDA"},
      {"Code": "BT", "name": "BHUTAN"},
      {"Code": "BO", "name": "BOLIVIE"},
      {"Code": "BA", "name": "BOSNIE-ET-HERZÉGOVINE"},
      {"Code": "BW", "name": "BOTSWANA"},
      {"Code": "BV", "name": "ÎLE DE BOUVET"},
      {"Code": "BR", "name": "BRÉSIL"},
      {"Code": "IO", "name": "TERRITOIRE DE L'OCÉAN INDIEN BRITANNIQUE"},
      {"Code": "BN", "name": "BRUNEI DARUSSALAM"},
      {"Code": "BG", "name": "BULGARIE"},
      {"Code": "BF", "name": "BURKINA FASO"},
      {"Code": "BI", "name": "BURUNDI"},
      {"Code": "KH", "name": "CAMBODIA"},
      {"Code": "CM", "name": "CAMEROUN"},
      {"Code": "CA", "name": "CANADA"},
      {"Code": "CV", "name": "CAP VERT"},
      {"Code": "KY", "name": "ÎLES CAYMAN"},
      {"Code": "CF", "name": "RÉPUBLIQUE CENTRAFRICAINE"},
      {"Code": "TD", "name": "TCHAD"},
      {"Code": "CL", "name": "TCHILI"},
      {"Code": "CN", "name": "CHINE"},
      {"Code": "CX", "name": "CHRISTMAS ISLAND"},
      {"Code": "CC", "name": "COCOS (KEELING) ISLANDS ``Îles"},
      {"Code": "CO", "name": "COLOMBIE"},
      {"Code": "KM", "name": "COMORES"},
      {"Code": "CG", "name": "CONGO"},
      {"Code": "CD", "name": "CONGO, THE DEMOCRATIC REPUBL"},
      {"Code": "CK", "name": "ILES COOK"},
      {"Code": "CR", "name": "COSTA RICA"},
      {"Code": "CI", "name": "COTE D'IVOIRE"},
      {"Code": "HR", "name": "CROATIE"},
      {"Code": "CU", "name": "CUBA"},
      {"Code": "CY", "name": "CHYPRE"},
      {"Code": "CZ", "name": "RÉPUBLIQUE TCHÈQUE"},
      {"Code": "DK", "name": "DANEMARK"},
      {"Code": "DJ", "name": "DJIBOUTI"},
      {"Code": "DM", "name": "DOMINIQUE"},
      {"Code": "DO", "name": "RÉPUBLIQUE DOMINICAINE"},
      {"Code": "EC", "name": "ÉQUATEUR"},
      {"Code": "EG", "name": "EGYPTE"},
      {"Code": "SV", "name": "EL SALVADOR"},
      {"Code": "GQ", "name": "GUINÉE ÉQUATORIALE"},
      {"Code": "ER", "name": "ERITREA"},
      {"Code": "EE", "name": "ESTONIE"},
      {"Code": "ET", "name": "ETHIOPIE"},
      {"Code": "FK", "name": "FALKLAND (ÎLES)"},
      {"Code": "FO", "name": "ÎLES FAROE"},
      {"Code": "FJ", "name": "FIJI"},
      {"Code": "FI", "name": "FINLANDE"},
      {"Code": "FR", "name": "FRANCE"},
      {"Code": "GF", "name": "GUIANA FRANÇAISE"},
      {"Code": "PF", "name": "POLYNÉSIE FRANÇAISE"},
      {"Code": "TF", "name": "TERRITOIRES FRANÇAIS DU SUD"},
      {"Code": "GA", "name": "GABON"},
      {"Code": "GM", "name": "GAMBIE"},
      {"Code": "GE", "name": "GEORGIE"},
      {"Code": "DE", "name": "ALLEMAGNE"},
      {"Code": "GH", "name": "GHANA"},
      {"Code": "GI", "name": "GIBRALTAR"},
      {"Code": "GR", "name": "GRÈCE"},
      {"Code": "GL", "name": "GREENLAND"},
      {"Code": "GD", "name": "GRENADA"},
      {"Code": "GP", "name": "GUADELOUPE"},
      {"Code": "GU", "name": "GUAM"},
      {"Code": "GT", "name": "GUATEMALA"},
      {"Code": "GN", "name": "GUINÉE"},
      {"Code": "GW", "name": "GUINEA-BISSAU"},
      {"Code": "GY", "name": "GUYANA"},
      {"Code": "HT", "name": "HAÏTI"},
      {"Code": "HM", "name": "ÎLE DE HEARD ET ISLA MCDONALD"},
      {"Code": "VA", "name": "SAINTE-SEE (VILLE DU VATICAN ETATVille Etat)"},
      {"Code": "HN", "name": "HONDURAS"},
      {"Code": "HK", "name": "HONG KONG"},
      {"Code": "HU", "name": "HUNGARY"},
      {"Code": "IS", "name": "ISLANDE"},
      {"Code": "IN", "name": "INDE"},
      {"Code": "ID", "name": "INDONESIE"},
      {"Code": "IR", "name": "IRAN"},
      {"Code": "IQ", "name": "IRAQ"},
      {"Code": "IE", "name": "IRLANDE"},
      {"Code": "IL", "name": "ISRAËL"},
      {"Code": "IT", "name": "ITALIE"},
      {"Code": "JM", "name": "JAMAÏQUE"},
      {"Code": "JP", "name": "JAPON"},
      {"Code": "JO", "name": "JORDANIE"},
      {"Code": "KZ", "name": "KAZAKHSTAN"},
      {"Code": "KE", "name": "KENYA"},
      {"Code": "KI", "name": "KIRIBATI"},
      {"Code": "KP", "name": "CORÉE"},
      {"Code": "KR", "name": "CORÉE"},
      {"Code": "KW", "name": "KUWAIT"},
      {"Code": "KG", "name": "KYRGYZSTAN"},
      {"Code": "LA", "name": "RÉPUBLIQUE DÉMOCRATIQUE POPULAIRE LAO"},
      {"Code": "LV", "name": "LETTONIE"},
      {"Code": "LB", "name": "LIBAN"},
      {"Code": "LS", "name": "LESOTHO"},
      {"Code": "LR", "name": "LIBERIA"},
      {"Code": "LY", "name": "LIBYE ARAB JAMAHIRIYA"},
      {"Code": "LI", "name": "LIECHTENSTEIN"},
      {"Code": "LT", "name": "LITUANIE"},
      {"Code": "LU", "name": "LUXEMBOURG"},
      {"Code": "MO", "name": "MACAO"},
      {"Code": "MK", "name": "MACEDONIE"},
      {"Code": "MG", "name": "MADAGASCAR"},
      {"Code": "MW", "name": "MALAWI"},
      {"Code": "MY", "name": "MALAISIE"},
      {"Code": "MV", "name": "MALDIVES"},
      {"Code": "ML", "name": "MALI"},
      {"Code": "MT", "name": "MALTE"},
      {"Code": "MH", "name": "MARSHALL ISLANDS"},
      {"Code": "MQ", "name": "MARTINIQUE"},
      {"Code": "MR", "name": "MAURITANIE"},
      {"Code": "MU", "name": "MAURICE"},
      {"Code": "YT", "name": "MAYOTTE"},
      {"Code": "MX", "name": "MEXICO"},
      {"Code": "FM", "name": "MICRONESIE"},
      {"Code": "MC", "name": "MONACO"},
      {"Code": "MN", "name": "MONGOLIE"},
      {"Code": "MS", "name": "MONTSERRAT"},
      {"Code": "MA", "name": "MAROC"},
      {"Code": "MZ", "name": "MOZAMBIQUE"},
      {"Code": "MM", "name": "MYANMAR"},
      {"Code": "NA", "name": "NAMIBIE"},
      {"Code": "NR", "name": "NAURU"},
      {"Code": "NP", "name": "NEPAL"},
      {"Code": "NL", "name": "PAYS-BAS"},
      {"Code": "AN", "name": "ANTILLES NÉERLANDAISES"},
      {"Code": "NC", "name": "NOUVELLE CALEDONIE"},
      {"Code": "NZ", "name": "NOUVELLE-ZÉLANDE"},
      {"Code": "NI", "name": "NICARAGUA"},
      {"Code": "NE", "name": "NIGER"},
      {"Code": "NG", "name": "NIGERIA"},
      {"Code": "NU", "name": "NIUE"},
      {"Code": "NF", "name": "NORFOLK ISLAND"},
      {"Code": "MP", "name": "ÎLES MARIANNES DU NORD"},
      {"Code": "NO", "name": ""},
      {"Code": "OM", "name": "OMAN"},
      {"Code": "PK", "name": "PAKISTAN"},
      {"Code": "PW", "name": "PALAU"},
      {"Code": "PS", "name": "TERRITOIRE PALESTIN PALESTINIEN"},
      {"Code": "PA", "name": "PANAMA"},
      {"Code": "PG", "name": "PAPOUASIE NOUVELLE GUINÉE"},
      {"Code": "PY", "name": "PARAGUAY"},
      {"Code": "PE", "name": "PÉROU"},
      {"Code": "PH", "name": "PHILIPPINES"},
      {"Code": "PN", "name": "PITCAIRN"},
      {"Code": "PL", "name": "POLOGNE"},
      {"Code": "PT", "name": "PORTUGAL"},
      {"Code": "PR", "name": "PUERTO RICO"},
      {"Code": "QA", "name": "QATAR"},
      {"Code": "RE", "name": "REUNION"},
      {"Code": "RO", "name": "ROUMANIE"},
      {"Code": "RU", "name": "FÉDÉRATION DE RUSSIE"},
      {"Code": "RW", "name": "RWANDA"},
      {"Code": "SH", "name": "SAINT HELENA"},
      {"Code": "KN", "name": "SAINT KITTS ET NEVIS"},
      {"Code": "LC", "name": "SAINT LUCIE"},
      {"Code": "PM", "name": "SAINT PIERRE ET MIQUELON"},
      {"Code": "VC", "name": "SAINT VINCENT ET LA GRENADINE"},
      {"Code": "WS", "name": "SAMOA"},
      {"Code": "SM", "name": "SAN MARINO"},
      {"Code": "ST", "name": "SAO TOME ET PRINCIPE"},
      {"Code": "SA", "name": "ARABIE SAOUDITE"},
      {"Code": "SN", "name": "SENEGAL"},
      {"Code": "CS", "name": "SERBIE ET MONTÉNÉGRO"},
      {"Code": "SC", "name": "SEYCHELLES"},
      {"Code": "SL", "name": "SIERRA LEONE"},
      {"Code": "SG", "name": "SINGAPOUR"},
      {"Code": "SK", "name": "SLOVAQUIE"},
      {"Code": "SI", "name": "SLOVÉNIE"},
      {"Code": "SB", "name": "SOLOMON ISLANDS"},
      {"Code": "SO", "name": "SOMALIE"},
      {"Code": "ZA", "name": "AFRIQUE DU SUD"},
      {"Code": "GS", "name": "GEORGIE DU SUD"},
      {"Code": "ES", "name": "ESPAGNE"},
      {"Code": "LK", "name": "SRI LANKA"},
      {"Code": "SD", "name": "SOUDAN"},
      {"Code": "SR", "name": "SURINAME"},
      {"Code": "SJ", "name": "SVALBARD ET JAN MAYEN"},
      {"Code": "SZ", "name": "SWAZILAND"},
      {"Code": "SE", "name": "SUÈDE"},
      {"Code": "CH", "name": "SUISSE"},
      {"Code": "SY", "name": "RÉPUBLIQUE ARABE SYRIENNE"},
      {"Code": "TW", "name": "TAIWAN, PROVINCE DE CHIN"},
      {"Code": "TJ", "name": "TAJIKISTAN"},
      {"Code": "TZ", "name": "TANZANIE, RÉPUBLIQUE UNIE DERépublique de"},
      {"Code": "TH", "name": "THAILANDE"},
      {"Code": "TL", "name": "TIMOR-LESTE"},
      {"Code": "TG", "name": "TOGO"},
      {"Code": "TK", "name": "TOKELAU"},
      {"Code": "TO", "name": "TONGA"},
      {"Code": "TT", "name": "TRINIDAD ET TOBAGO"},
      {"Code": "TN", "name": "TUNISIE"},
      {"Code": "TR", "name": "TURQUIE"},
      {"Code": "TM", "name": "TURKMENISTAN"},
      {"Code": "TC", "name": "ÎLES TURQUES ET CAÏCOS"},
      {"Code": "TV", "name": "TUVALU"},
      {"Code": "UG", "name": "OUGANDA"},
      {"Code": "UA", "name": "UKRAINE"},
      {"Code": "AE", "name": "ÉMIRATS ARABES UNIS"},
      {"Code": "GB", "name": "ROYAUME-UNI"},
      {"Code": "US", "name": "ÉTATS-UNIS"},
      {"Code": "UM", "name": "ÉTATS-UNIS ÎLES MINEURES ÉLOIGNÉES"},
      {"Code": "UY", "name": "URUGUAY"},
      {"Code": "UZ", "name": "UZBEKISTAN"},
      {"Code": "VU", "name": "VANUATU"},
      {"Code": "VE", "name": "VENEZUELA"},
      {"Code": "VN", "name": "VIET NAM"},
      {"Code": "VG", "name": "ÎLES VIRGIN"},
      {"Code": "VI", "name": "ÎLES VIRGIN"},
      {"Code": "WF", "name": "WALLIS ET FUTUNA"},
      {"Code": "EH", "name": "SAHARA OCCIDENTAL"},
      {"Code": "YE", "name": "YEMEN"},
      {"Code": "ZM", "name": "ZAMBIE"},
      {"Code": "ZW", "name": "ZIMBABWE"},
      {"Code": "RS", "name": "SERBIE"},
      {"Code": "AP", "name": "RÉGION ASIE-PACIFIQUE"},
      {"Code": "ME", "name": "MONTENEGRO"},
      {"Code": "AX", "name": "ÎLES ALANDES"},
      {"Code": "BQ", "name": "BONAIR"},
      {"Code": "CW", "name": "CURACAO"},
      {"Code": "GG", "name": "GUERNSEY"},
      {"Code": "IM", "name": "ÎLE DE MAN"},
      {"Code": "JE", "name": "JERSEY"},
      {"Code": "XK", "name": "KOSOVO"},
      {"Code": "BL", "name": "SAINT BARTHELEMY"},
      {"Code": "MF", "name": "SAINT MARTIN"},
      {"Code": "SX", "name": "SINT MAARTEN"},
      {"Code": "SS", "name": "SOUDAN DU SUD"},
    ]
}
